import { Component, OnInit } from '@angular/core';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

//Mirror the backend model
interface Spending {
  spending_id?: number; // auto-generated by the database
  spending_amount: number;
  spending_date: Date;
  spending_desc?: string; // optional description
  user_id: number;
  category_id: number;
}

interface User {
  user_id?: number; // auto-generated by the database
  user_name: string;
  user_email?: string;
}

interface Category {
  category_id?: number; // auto-generated by the database
  category_name: string;
  category_desc?: string; // optional description
}

@Component({
  selector: 'app-spending-tracker',
  standalone: true,
  imports: [CommonModule, FormsModule, HttpClientModule],
  templateUrl: './spending-tracker.component.html',
  styleUrl: './spending-tracker.component.css'
})
export class SpendingTrackerComponent implements OnInit{
  categories: Category[] = [];
  spendings: Spending[] = [];
  users: User[] = [];
  newSpending: Spending = this.initializeSpending();
  newUser: User = this.initializeUser();
  newCategory: Category = this.initializeCategory();
  editSpending: Spending | null = null;
  editUser: User | null = null;
  editCategory: Category | null = null;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.fetchCategories();
    this.fetchUsers();
    this.fetchSpendings();
  }

  fetchCategories() {
    this.http.get<Category[]>('http://localhost:3000/api/categories').subscribe((data) => {
      this.categories = data;
    },
    (error) => {
      console.error('Error fetching categories:', error);
    }
  );
  }

  fetchUsers() {
    this.http.get<User[]>('http://localhost:3000/api/users').subscribe((data) => {
      this.users = data;
    },
    (error) => {
      console.error('Error fetching users:', error);
    }
  );
  }

  fetchSpendings() {
    this.http.get<Spending[]>('http://localhost:3000/api/spendings').subscribe((data) => {
      this.spendings = data;
    },
    (error) => {
      console.error('Error fetching spendings:', error);
    }
  );
  }
  /*
  Method for update user
  */
  startEditingUser(user: User) {
    if (this.isFirstUser(user)) {
      console.warn('Cannot edit the first user');
      return;
    }
    this.editUser = { ...user };
  }

  startEditingCategory(category: Category) {
    this.editCategory = { ...category };
  }

  startEditingSpending(spending: Spending) {
    this.editSpending = { ...spending };
  }

  cancelEditingSpending() {
    this.editSpending = this.initializeSpending();
  }

  cancelEditingUser() {
    this.editUser = this.initializeUser();
  }

  cancelEditingCategory() {
    this.editCategory = this.initializeCategory();
  }

  // Ends here

  initializeSpending(): Spending {
    return {
      spending_amount: 0,
      spending_date: new Date(),
      user_id: 1,
      category_id: 1
    };
  }

  initializeUser(): User {
    return {
      user_name: '',
      user_email: ''
    };
  }

  initializeCategory(): Category {
    return {
      category_name: '',
      category_desc: ''
    };
  }

  getUserName(userId: number): string {
    const user = this.users.find(u => u.user_id === userId);
    return user ? user.user_name : 'Unknown';
  }
  
  getCategoryName(categoryId: number): string {
    const category = this.categories.find(c => c.category_id === categoryId);
    return category ? category.category_name : 'Unknown';
  }

  submitSpending() {
    this.http.post<Spending>('http://localhost:3000/api/spendings', this.newSpending).subscribe(
      (response) => {
        console.log('Spending added successfully:', response);
        this.spendings.push(response);
        this.newSpending = this.initializeSpending();
      },
      (error) => {
        console.error('Error adding spending:', error);
      }
    );
  }

  deleteSpending(spendingId: number) {
    this.http.delete(`http://localhost:3000/api/spendings/${spendingId}`).subscribe(
      () => {
        console.log('Spending deleted successfully');
        this.fetchSpendings();
      },
      (error) => {
        console.error('Error deleting spending:', error);
      }
    );
  } 

  updateSpending() {
    if (this.editSpending === null) {
      console.warn('No spending to update');
      return;
    }
    this.http.put(`http://localhost:3000/api/spendings/${this.editSpending.spending_id}`, this.editSpending).subscribe(
      () => {
        console.log('Spending updated successfully');
        this.fetchSpendings();
        this.editSpending = null;
      },
      (error) => {
        console.error('Error updating spending:', error);
      }
    );
  }

  submitUser() {
    this.http.post<User>('http://localhost:3000/api/users', this.newUser).subscribe(
      (response) => {
        console.log('User added successfully:', response);
        this.users.push(response);
        this.newUser = this.initializeUser();
      },
      (error) => {
        console.error('Error adding user:', error);
      }
    );
  }

  isFirstUser(user: User): boolean {
    return this.users.length > 0 && this.users[0].user_id === user.user_id;
  }

  updateUser() {
    if (this.editUser === null) {
      console.warn('No user to update');
      return;
    }
    this.http.put(`http://localhost:3000/api/users/${this.editUser.user_id}`, this.editUser).subscribe(
      () => {
        console.log('User updated successfully');
        this.fetchUsers();
        this.editUser = null;
      },
      (error) => {
        console.error('Error updating user:', error);
      }
    );
  }

  deleteUser(userId: number) {
    this.http.delete(`http://localhost:3000/api/users/${userId}`).subscribe(
      () => {
        console.log('User deleted successfully');
        this.fetchUsers();
      },
      (error) => {
        console.error('Error deleting user:', error);
      }
    );
  }

  submitCategory() {
    this.http.post<Category>('http://localhost:3000/api/categories', this.newCategory).subscribe(
      (response) => {
        console.log('Category added successfully:', response);
        this.categories.push(response);
        this.newCategory = this.initializeCategory();
      },
      (error) => {
        console.error('Error adding category:', error);
      }
    );
  }

  updateCategory() {
    if (this.editCategory === null) {
      console.warn('No category to update');
      return;
    }
      this.http.put(`http://localhost:3000/api/categories/${this.editCategory.category_id}`, this.editCategory).subscribe(
      () => {
        console.log('Category updated successfully');
        this.fetchCategories();
        this.editCategory = null;
      },
      (error) => {
        console.error('Error updating category:', error);
      }
    );
  }

  deleteCategory(categoryId: number) {
    this.http.delete(`http://localhost:3000/api/categories/${categoryId}`).subscribe(
      () => {
        console.log('Category deleted successfully');
        this.fetchCategories();
      },
      (error) => {
        console.error('Error deleting category:', error);
      }
    );
  }




}
